# Generated by Django 2.2.7 on 2019-12-30 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
